logging:
  level:
    root: INFO
loggin:
  level:
    org:
      springframework: INFO
spring:
  serialization:
  jackson:
    write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: "*"